#! /bin/sh

# This is the command to generate the automake stuff the first time.
# After the first time, if you do configure with --enable-maintainer-mode
# then then the generate makefile will automatically rerun the autoconf
# stuff that might be needed when you change something up stream (like 
# configure.in)

aclocal -I config/m4 \
&& glibtoolize \
&& automake --gnu --add-missing \
&& autoconf

# Can also redo with something like:
# autoreconf -I config/m4
# or
# autoreconf --install --force -I config/m4 (to update files after updating autools)
