.TH Vm_InitFormat 3 "22 Oct 1992" "TAE Plus v5.3"
.SH NAME
Vm_InitFormat - initialize for formatting variables; for Terminal Monitor

.SH DESCRIPTION
.IP
.LP
VOID Vm_InitFormat (vmid)

Function return:

.IP o
None.
.LP

.IP
.LP
Argument:

.nr L 0 1
.IP \n+L.
vmid: input, Id   vmid;

Id of a Vm object which contains TCL variables.  
.LP

.IP
.LP
Vm_InitFormat initializes for use of Vm_FormatVar.


.so man1/../COPYRIGHT
.so man1/../AUTHOR
